name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build dev image
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: okteto/aspnetcore-getting-started:dev
          target: dev
          context: ./hello-world
      - name: Build prod image
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: okteto/aspnetcore-getting-started:hello-world
          context: ./hello-world
